name: Auto Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  auto-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add explicit permissions for repository operations

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
